export const MATERIAL_ICONS_TO_SF_SYMBOLS = {
  'format-size': 'textformat.size',
  'drive-file-rename-outline': 'rectangle.and.pencil.and.ellipsis',
  'restore-from-trash': 'arrow.up.trash.fill',
  'folder-open': 'folder',
  'file-copy': 'doc.on.clipboard.fill',
  'menu-book': 'menucard.fill',
  backpack: 'backpack.fill',
  'person-outline': 'person',
  person: 'person.fill',
  accessibility: 'accessibility',
  'nightlight-round': 'moon.fill',
  'card-giftcard': 'giftcard',
  router: 'wifi.router.fill',
  'live-tv': 'play.tv',
  'connected-tv': 'tv.badge.wifi',
  'alternate-email': 'at',
  'check-box': 'checkmark.square.fill',
  'attach-money': 'dollarsign',
} as const;
